version: "3.9"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "8080:8080"
    networks:
      - app-network

  db:
    image: "postgres:12-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: typoteka
      POSTGRES_USER: postgres
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
